apiVersion: v1
kind: Secret
metadata:
  name: google-auth
  labels:
    {{- include "otterwiki.labels" . | nindent 4 }}
type: Opaque
data:
  GOOGLE_CLIENT_ID: {{ .Values.oidc.google_client_id | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oidc.google_client_secret | b64enc }}
