name: Build

on:
  workflow_call:
    inputs:
      tags:
        type: string
        description: The Docker Tags (see docker/metadata-action@v4 for available values)
        required: true

jobs:
  build-push-otterwiki:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Build/Push
      uses: coopTilleuls/action-docker-build-push@v10
      with:
        IMAGE_NAME: otterwiki
        ÃŸUILD_CONTEXT: .
        REGISTRY_JSON_KEY: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPOSITORY: ghcr.io/cooptilleuls
        # Deactivate Trivy
        SECURITY_SCAN: "false"

